# Generated by Django 4.1 on 2023-12-16 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_cart"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="cart",
            new_name="cartIt",
        ),
    ]
