# Generated by Django 4.1 on 2023-12-16 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_rename_orderitem_cartitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order",
            new_name="Cart",
        ),
    ]
