# Generated by Django 4.1 on 2023-12-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_remove_purchaseinfo_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinfo",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.order",
            ),
        ),
    ]
