# Generated by Django 4.1 on 2023-12-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_rename_date_added_purchaseinfo_date_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinfo",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.product",
            ),
        ),
    ]
