# Generated by Django 4.1 on 2023-12-18 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0018_remove_purchaseinfo_order_orderedproduct_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="digital",
        ),
    ]
