# Generated by Django 4.1 on 2023-12-18 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0019_remove_product_digital"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order",
            new_name="Cart",
        ),
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="CartItem",
        ),
    ]
