# Generated by Django 4.1 on 2023-12-18 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0020_rename_order_cart_rename_orderitem_cartitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cart",
            new_name="Order",
        ),
        migrations.RenameModel(
            old_name="CartItem",
            new_name="OrderItem",
        ),
    ]
