# Generated by Django 4.1 on 2023-12-18 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0021_rename_cart_order_rename_cartitem_orderitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="CartItem",
        ),
    ]
