# Generated by Django 4.1 on 2023-12-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0023_product_description_userrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
