# Generated by Django 4.1 on 2023-12-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0024_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedproduct",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.customer",
            ),
        ),
    ]
